language: node_js
sudo: required
before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in se234.pem.enc -out se234.pem
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script:
- docker build -t dto80/htmltest .
- docker push dto/htmltest
after_success:
- ls -l
- scp -i "se234.pem" -r html/* ubuntu@54.187.89.205:/var/www/html/
- docker run -p 8088:80 -d dto/htmltest:latest
service: docker

env:
  global:
  - secure: i+pGimOkNL5rEXuKa+xD8fMUaLduja7yykrVKf3Ukug+hBiFhOlieN1sCdNXVqv5BQiIXDZEuvxQpF6C2VgbbIRxYC38DCpi/GC4pEM+U6s8iO4VWi1+5npsvFKDk8MDmi6SLmFlSieMNA08FUsGxarIOUturUxyEHk5csdPiL8WyVCqhVSjEP1++CsvdNaaBcPyS/PqlkVeOn/lNz/j3p1AN3kLrz3qTdJFGxAiytp3W++FuI5IlrxDY1ygO5cavX8MdcQ9mpKcrzrWcMOhBwJ2Q9Tl00AHy30HF71gXkubsNJzUz5hWT+ZJCzpi26F93ShdY5XmltRk47QDAzcFfISwaiVYcjDZEsv1jIW910l8yNXznnaMmY3OnCIc1fRxAWlbmI+hZCEXVrZPHo1bwrjNPY4LahBRyr7/zvcReql/8aXgvycmBdHQyoexlklUnveh5TO6YQcGk/uIXLzutXiOA8NzYPC6vEa5JB23ZYfCDh46AtCQUTIqX4AjQ4y71eWx7X4UcofFFCYFMvsJAzuKwhWKpDHPszKPdP9S9uPogSjiJMudU4kEopLi7jBice7aHAw/Vbkfz2bfQuCXQdMyOQKeHbVWVzBk5AGsnI+gLofGcoklPPPRvMooGiMAt3uuEp3JtYr0ABP52Q2kiMF7AQE+XYjqkkuqUCIw20=
  - secure: lVcwWxrcDHPzsQz0xRLizb++8dOOGEDUUnf99K5+5BsrKCyx1H9qicUBdVcN8a2npOhh7ft4wHva//FsVRdIj316UnUbTtDWWldoMsMfswi5vWwoTyAKgabbBMkCPI16tr5zcB7yGdySVha7VfOgCkKwqj4QwiF3N0Wc5FEBo5COe/BsOjVwY+YKZltUu3FqaLQXVmm9enuem+9W12A4mU2pxTFgt22CfOMSgFnFYDYX4ZMVrxD2MgKzRIxF47xmlXKt+2lYMjgV0O1GGWPz4FvhUXqxOYvpBXMUlv6vZZHnpBF8v7QqD5L/aiY+hX3AASBLMOOe4YdxF0CfmPoIOW9DRMPG1pU8jbAHwMB6EpsRkXVkNz5mGuY0fWUU3MIxw365DhVxE1JyThQiP8qsVZTcHjtDILwXoAhLvz2Yug+xTbUH80Pf8z+2iIp7Bxbv8Tg+vcJ3Ul1TVLWUPPe3wpT4Idmtt3DxCf2jxebeLTNFZqaINUNucstmpdv3ZZiX0eNCLhqWA58TmYQDmW2XgTdt4/iPMMccIb/M/fwy+ghO7ueNPaYc95tz3A0//cpWvL2Oe0AqmJUFA1eNH+JxFDzdDqacYDrUHXnDtkYC+YR7LyBD4XuMTKFYM04YfKjFOl6eguHunraN7a0yMrVMlgtEJjzh6AAVAi0vlvXWMAo=
  - secure: jjxon0QdiWVvCvsdUHr02hk+9y+53kMF04xy93Gj1Z1nbCcXOAcw5WguYvk8Q0M2YEkFKZLLpwNGarKdgRaFnArHLTGBvdFEpWCmNLLDiGxFzLdIn3IS67hpAY624TVOYxB0P4cPBfW43KU9DI/n9pyjzU09LrFrounR3d4EyGXVQe//8WFFA2J+d9OxXGa8w/Q/C+TVvEKVvRfn+YR6UW65iYhhs+Ln9Y8rYCMhi6IldGbDEZEijeOEISSy6ZRMZAnYHI+l66Y56FxHG3D1FabgISMSdXGWLf0h3XdrLq2T44BM1aP5sU5zPMGZ7UQOK7aNbaCGU0rMZOLzOQrFheKZC0w85FLO62RJmM/e2M2V18qwZuKh//GtFTLnf7YP0s+E5zn9B40ZZbhoI5YN2urP+89OgiC2qnvQ2sfrSF1Q53UWk29y3I7b3COutpQDENtvLqyyMegdluZp/0Aa0XQT4Q3pAvh8EHbiSqB0XcdcrQRpl3xfdXP8KOUSKJkb6hVxE/wCNeTG+QneU7KnhIRzE8/cn2bbqtHzGC9fZ9tK0gCKG6Hr0MlXrFyRBfUu2yYcRMSGRWEvtZOuEPtpU6F/rpnPvWxMwML5uXVtfWClLpyl2RJoxYqysUh/5hzrJubiGXtCxo+vfMUf8TL9bv9D9xhUC5CQ0/PGgAh/LNs=
  - secure: nq/xIRQzW4/csQmPxTiIjqD3TQuGYwcs8PgySbKV32ivqN4ivJjMUE0Hg//v8bzQrr9tTCJmYj34OopQvZlpFXCGcvHwugrwiJh4sZU5G5Guu61c6jYKraYF589a31ZqjScRDzN6gx3VAG63iDGQmy8FVU4Yv0O0pVjjqiZ7WS66fSb23QUYj8KvEjvHBpqfqpeAYNRf/sljoTL3vHT9I//+nFA1foxUL97mIMXEfWJX86vRCKRa6UwjjQArYVw0sdvHmrTZPk4mmyp/sMk9mS2wvHgZwsi7reiu8gDesaLiRAN/hQrqaPlYzpUK3X3neYA4BhXztseGAVaGtIdEZt4yVh+FjDhILoUpMrPdAfsI2G480s6Rt6s2JU3X99uT+80bkK85C05JmcXqXgMXURb4Ik5jIWxsYYcXPy1uURs2FcHYcb0/MsIWbesGKqQw2XmIP2E1gL+WjVcGP+4ZIJq/KR6m4TeHKuFQVlwTluV2g9iGdQ9pSKkFePdgDiD1wAkx8tAb54vEUBuUwc4ZlkXinYYnzhOW3uD/btCq5LHvvggy+TIRsSuY40ryfIhcCoQ5iYOEOYOflzBKDhcvqcNsKaV5GnqXVCagHQ6kWod08TcEo+XgYRLeXB0LWbCuTBfacBsirPxrvTGTogf1lzTzjGOAlnHXzJ/QO4NEBQM=


addons:
  ssh_known_hosts:
  - 54.187.89.205
