language: node_js
sudo: required
before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in se234.pem.enc -out se234.pem
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script:
- docker build -t dto80/htmltest .
- docker push dto/htmltest
after_success:
- ls -l
- scp -i "se234.pem" -r html/* ubuntu@54.187.89.205:/var/www/html/
- docker run -p 8088:80 -d dto/htmltest:latest
service: docker
env:
  global:
    secure: BWAvzVtOEesnwbw2dwM86jIJDDVPFVTg2pHGIaz9pey2Fp76ttLE/2j7UzUL3W9PTJavlSU05QsO+iCb6lJTRnqBjxgFU1JBRz06KDE07FT8xyvX6iiCzjO1gbblmoy92sd3g9pIKLhL5zqciaCLMmEYqRg4qwnNapByG1/D1YI1XZ5jgA2cLUTpFZR0QIPj8FcCIO0Az8zOO9oID+HsT0Fqz36ryY5Zc/dj9H+Yzf7MU3b4E2b4hcPEAIkTnpwQufg6s6Ykn3zlIi3HPjcwKRXuLDRJLsu6oHu0rtk1oFDDTtJrCWnMFzJjCqIylwRCJc0Ct0gXDKCJkd40z3sNF3y6HGWWP0ms2cW1W3ahVmet7AtzFkczf3Vu4C0sSqtyXTqbK9/XaEYgKXXV03r4q4sMJZOVDjsw1I5r94DFFGBIBNAF0uV/TzWO/SWraDZXlzfY/H+Kiu3eG24sirDKMWKaLjOSmofQM6Wffe3H1J5N9ipIWwjKiFWxTECBLBf3xaA3aOHnSD42VLYCsNEyhTWP4p2/Wxgkst/HdIsW5VmGuLTi7zY5wKEcM0WJj1cmezdLGemhU1R/F8PMlVJHwwk4EcG9NYi9+mhMnPX8Gi2HWvrgbU7D8+YIOoVbqKebeUj3BTA2DUrkYznCBOfUGUhjt5QwVbItRTZYmrzoPD4=
    secure: ebtjmJm3B3dmCz95EZikg12iy3WKunJJvrJOUOxiBjZr4p7NOUPMXbsY5Xa1pDpPTRC8AnX5COixU8q3ISCbDQ8JNVhEQZxD5Y9oh9ALuZMtQOftybRMdVD5ZWjMn8mx7KWRMRgLsNgEFOmR1PwVCfMUbayUXDUUd93/P1QX8SC/1xCzi7ked+lC5rsrtOwgHZW44YT+T8XtxBUEFwpBtfbALUaUrYt4qZpqoLPofbLuqecVR3K6V0TubTPqL5VGK2aizqkTuTB5kl9nufgIHXRBFGZN1EH6vFTA6y59JFs5bf/mKeq6p0zJwCMqV57ti2la2gHlqocG58tZXkN2udZJs2ICSW1cWQXmJAXLZOZCeJcxeQe7+qFGJ1LDOAGMc44HRGTALV7mvrTnGhC6FLN8kNKFRoqLbjg9NDb2NweG1/1CMAnwv3uxDBfsFz8KMP3H3EPj+EIPia3ScLhzxQ8Zji6TD4RaTJp4J8N0BBhsru6GwXyJakVPeATWQWgzryAz4NLTsGsTMy1H3kdsCSlOnFwsZfY2c5g3IeruQzX7XxuJ1qeiK7MRUC/4INGMvDoTP4al++8LO6Q0ZHOfMRC33JcA5+YFQ6CMKKbEp612PNVwO+iBUIBdyJXHi1pJoTBICjiR0Kq/5Ld58a+DtYFsPJwmcfrBANFCwzA1/98=
    secure: cuTSNHj0TI7PLC4dP5JOM8pjAFyccqWJX7tajrVkr4Pt3eacfuH/qM7QHNNDxTuAA3wXQVTIxBEZnbQtBY6O99rS9Aw0DyKeetHb2e22tLHrgPCRReS1NjD/viLCmPg9MGVJjZ3Da3PiwGA65YcCQ5mvlqK3pGOPlakuA1HzNJ183832yiU67rX0aITBnozJDw4A3KXXpBSSA81GwieUbUVxcrDYgZy7K2xo+maEPqJ1KeEDjmu7S4OMu45L3vCwFZtSTpWvLRVSbti5ujJ0hHvbJ9TNXGg3JOr7X1CjrcsRT4GIuur2lFBNnNgHi0vng0PFG2iz6SiwdCFIwDXYHtvj7wTPLKWuS5KNVYYYwj4PzyiP7ucWtRaHAlKzp4r0bsyqlLbdpENHSCjpTxc3LnQSEsv/paQmYOqdncBgfcV11f9ayOBrG1O6BuNQ9uKJTjJaUSRMrcvBgINKbcHijHpL3u/wKMgFtTW0j+oJLsKf2uwaP70fKvxmhIlsKj3BigOGaNnWV7dL99mZeGDbR6i+zabgaWHjdT5Y54c0phnjWPUNNz9g7rFwrZScqNGnplCsGq5Og50ktI8cG7Q2XIcX06RLQ+By5PXIduneJh6kFIuW8Fpk7tqDdF18a1P47RJebrEaekVtMLbj8VzBUOa2mQnk/Ekyqo98szNy4Jo=
addons:
  ssh_known_hosts:
  - 54.187.89.205
