language: node_js
sudo: required
before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in se234.pem.enc -out se234.pem
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script:
- docker build -t dto80/htmltest .
- docker push dto/htmltest
after_success:
- ls -l
- scp -i "se234.pem" -r html/* ubuntu@54.187.89.205:/var/www/html/
- docker run -p 8088:80 -d dto/htmltest:latest
service: docker
env:
  global:
  - secure: kVD9VnJqwaqxWQ0S2Ck2Lgnkc0aAkIqlWjqjW0QunEFvhE6w0cEYoq77YADfzFAUNabOsoK5aOxRgqViyjBsc+svG931r409+C6w4dybm1mqAfhjfYODFei47Xf3Q4IbpV7brZ+/Hmh/6AfUgYJrvMwg40SkKD7cmo4BRNA55a/wrkFfb6lUjIYgY2svvSp0N5Wr/iOtROoENB4FLRNrGjBA6k176mgdZ54xus0WBt9ewzbmKXAe7FGIZqDEirF2ykLILseh6M3j+p2gemn4ZK46K3pcp55LaTRSgCEF+Ql3TD6WZrG1TwOV3fCrkFy6yfyId7ceoYhfEtUs4uq73C3pZfcSHTNha2E1ZzmAbBTBTz0nsvr5rQmKaSRS0Mep+eltUaz1ZEFiT7nY+5+szBdFP+pg6fN2oX9wRq8sWesT0KIoeQzZK40o3I1nxZS6T3SkA9JTxybstbPBrOV6izNWkjAqCcacDjskhKoaP+b2pJ2MKr/jwmKhRgeE/AsUlG3QkcrCAlaVqetkupaSqaG43hyNLRPZhD6/GsSa0I6f3IXxBbdX6B+gdzC7u4Fu4w5yMLvaaU9QcGclXDXew6/EY243SQzeyQq0dgK69D/nzgIm3QxSNYZWpa57R0xMfE4n2ksB9yHeo2cS9gQSAiwz3JzxVGpt4LK+7UX1dBw=
  - secure: dPIWDj0MfEEU5bur6KMI9RXpadKpuFVpXYCvgkAZ9E+rs33wkmB7uUfsZynUaOV1injaUVZDip1bHGzHnqzUYKNiafvO9eNzNcjGopeeXBQEWX8AeatA7gobsV6Us6xBrbeYr+d2ALV9z9hfsHYoGaxSlaq3IZKXK7dhkZ07UWDELW5wxALbympR6cJe6a52u3X4bIPRdsFVPdwC4wZ1GlmsGgl38A7llZneuXY2iHSEVKc5SBpPu/ZrClHd12cOATmRMlxFMTxFMmHO1XQUwjATFOqW5X6Jf3QRHLs42vrw9HSgi0PrJ6KlB5JWpG0di2kDBfc51+JECXUdcEj1Y2noljQ2T2KCBwyJtOFFwGrAJ3U4Quog1KqbpZfuhj7lE7c5OVH7F2eJknrzEcU1wvWtODY6NMw/P7k0WbNDt9w1+AejxDqlYSmWV+iGHD+v552nkxOt3zHMbzn7fc3k4KTh7zcEV7bZZntygOUE73O8IIJ8lDS33bHHdSYgQ0sWw4KgQwCOBNTNEfnhtvlekhdCBsXZZ8YIPSmsbdk6O/I7TW0GAXpyjktVsSS1DinwePEzb25u90N0hwd/McN/lKyVY1Zyol9gSxcXlbpb777PJVajPy048s85+fjHhNIQuFJf1HPluU77YgEAa2QheX8ahE2ypQoMOiJZoRbCnz4=
  - secure: hN0EyFLzFmNuILLL5ol6k/K44LofM3TDSRnLpBNqn+0xfrXqm7WPZzHLMwxL/D2W14hpTigb6SmN+bpYLOPxSBBYMzmcELH38J8VsxZ4ZFi3UsuM802AWlMw1FulqXXqEmOhac/8BmsL+L2KOap31yUNdY2G+VV+nspY8kAYB9zWX3cRsUD20hMTW2KIHnhEeR3ivyjfz+i2zJ9/WvD/JvopABRMWJFJFInj/ZKZqNPLHAfG3SkxqJ86gL4Sq/PJ5/45TEdprzSoMj223IQwhfDztWxU2JaB/IYeawE8sUcUZeIg6NCknzP8sjgvs+N//4K6Ojmn9d7Dv5u758xKM5T2fgVHeodPEGgndNvRnTFMANdOYk2XiOvJxjDcVtPrz2FPZtJLCHMTQlaOwtfjdXgZ9ngfU5Dd/OqfaXcCW8nIH7z1KIB2B7/ZLm/VU4hi8blQMLRZudAcI6znkm2XqVoE0H6AZ0xl/U7zklUPSWMIDGu84RcpE2otwZMlo+p5AATnwOnYdHMJc9DWZ/DdJS9wQ0x0QKAAsa4bJ7uAYUslEhjRfCHJ9qZ+7IuwfJ61TziQfojrOB5I1252+ZjzPv+k/IGrnBH1vII0IWE5GOYCDrL6PFV7sWZQ9Vws/QrX46I20AxwVaWZaBWXX2VipskvgOUejAUQgRtL9Kwz/9o=
addons:
  ssh_known_hosts:
  - 54.187.89.205
